### ISSUE TITLE
People Image Sizing 

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/Sculpture-2015#10]
@dstrogiy should we force a set size for peoples images? in the comps everything is nice and exactly the same size which we can certainly do but just checking 

see example below 
<img width="879" alt="screen shot 2015-09-10 at 2 50 34 pm" src="https://cloud.githubusercontent.com/assets/1740634/9797892/9edd6226-57cb-11e5-9ee4-48f882b4b74b.png">

**Comment by dstrogiy** [comment]
I say yes, either force-resize or do a cover

**Comment by dstrogiy** [comment]
Nice pics

**Comment by streeetlamp** [comment]
ty :+1:
