### ISSUE TITLE
faculty filtering animation

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/Sculpture-2015#12]
the hiding and showing of faculty could use a simple fade or something to ease in/out

**Comment by dstrogiy** [comment]
Can we also make the active highlight consistent with other tertiary menus? I think it should be black with border underneath instead of current purple (unless we switch the default highlight to purple)

**Comment by dstrogiy** [comment]
Gotta do the animation via JS, since we're using display property to show & hide

**Comment by streeetlamp** [comment]
so faded
