### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/Sculpture-2015#13]
We gotta figure out what to do with it.
Popup/google? Or default wordpress? Ya know

**Comment by streeetlamp** [comment]
I was planning on a custom google search with probably popup / overlay results

**Comment by dstrogiy** [comment]
![picgifs-14-3d5419551a2816eac14e5fa17aae3d2c2e0f971d](https://cloud.githubusercontent.com/assets/6132788/9826058/834acdf2-58a5-11e5-98c4-69ee3bd7dc68.gif)

**Comment by streeetlamp** [comment]
Using a p cool framework called WP Advanced Search actually, very basic functionality has been implemented
