### ISSUE TITLE
Faculty archive page

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/Sculpture-2015#17]
- [ ] default thumbnail for people without an image?
- [x] ability to re-order categories & people (e.g. Matt should be the first one, etc)
- [x] Rename "expand bio" to "read more", since some don't have bios

**Comment by streeetlamp** [comment]
Ability to re-order can be handled by the re-order plugin, will enable it now

**Comment by streeetlamp** [comment]
Changed Expand Bio to View Profile (thought it sounded better?)

**Comment by dstrogiy** [comment]
![clot04641_3_324_2](https://cloud.githubusercontent.com/assets/6132788/9938784/02f1d79c-5d35-11e5-8bef-003fdc44162a.jpg)
