### ISSUE TITLE
Alumni archive should have Alumni nav link as active

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/Sculpture-2015#19]
\/ alumni should be active in nav 

![screen shot 2015-09-15 at 4 57 26 pm](https://cloud.githubusercontent.com/assets/1740634/9889895/e41b6b8c-5bca-11e5-9547-e3567b4cb868.png)

**Comment by dstrogiy** [comment]
Also need to display the alumni subnav

**Comment by dstrogiy** [comment]
![tumblr_n6c5wyk5vt1tviec6o1_1280](https://cloud.githubusercontent.com/assets/6132788/9993335/2a5e4f50-6045-11e5-85ee-c6fa88559469.gif)
