### ISSUE TITLE
Content Needs

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/Sculpture-2015#26]
- [x] Curious PDF downloads (google drive folder is confusing currently)
- [x] Finish Importing Visiting Artists

**Comment by dstrogiy** [comment]
- [ ] Alumni Profiles
- [ ] Alumni Contact
- [ ] Alumni History
- [ ] Alumni Support

**Comment by dstrogiy** [comment]
- [ ] Mailing list form on contact page
