### ISSUE TITLE
What's the plan for MFA portfolios?

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/Sculpture-2015#27]
Per Matt:
"We would like the Current MFA Students to have profiles like the Faculty: a brief bio, and image of their work, and a link to their website.  We do not have this info compiled yet, but their names and links can be found here: http://arts.vcu.edu/sculpture/portfolios/"

Is the plan to leave this as is until we get all content from Matt? Right now the list of names just link to students' websites.

**Comment by dstrogiy** [comment]
Yep, I've figured since they don't have that info yet, we can just do a static list for now? In the future we can use the good ole' template for the alumni, faculty, artists, etc

**Comment by PeytonSorah** [comment]
Sounds like a plan!
