### ISSUE TITLE
** Alumni Contact

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/Sculpture-2015#46]
"Remove the “Contact” section. It is redundant with the main “Contact" page. Needs to be removed from the menu and the body of the page."

Matt mentioned removing this, but I think that he has forgotten it is supposed to be a form for obtaining contact information from alumni and not giving contact information out. Probably needs to be a convo we have with him to double check that he still wants it.

**Comment by streeetlamp** [comment]
Yep this is dead
