### ISSUE TITLE
Search as a Service

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/Sculpture-2015#57]
The search could be improved — not 100% useful at the moment.

Example - when searching for "grants" it doesn't display any of the funding pages that mention grants several times.

**Comment by dstrogiy** [comment]
Also the loading gif

**Comment by dstrogiy** [comment]
The possible reason fo this is that the search isn't searching page content at the moment, just the title. Needs a tweak

**Comment by streeetlamp** [comment]
Search looks for ACF content now
