### ISSUE TITLE
Image Caption Support

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/Sculpture-2015#62]
A caption was added to the image on this page http://arts.vcu.edu/sculpture/ssp/
and its done borked responsiveness

**Comment by dstrogiy** [comment]
possible solution http://wordpress.stackexchange.com/questions/89221/removing-inline-styles-from-wp-caption-div

**Comment by dstrogiy** [comment]
![councildance5](https://cloud.githubusercontent.com/assets/6132788/10368462/4e460b5e-6da3-11e5-9983-dd2460a20da0.gif)
