### ISSUE TITLE
Visiting Artist URL field

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/Sculpture-2015#63]
http://arts.vcu.edu/sculpture/visiting-artists/

"Vito Acconci and A.L. Steiner's  links on the visiting artist page are going to an error page.  I looked in Wordpress to see if those urls had been entered correctly, and it appears that they have.  Is there a difference between the "Permalink" and the link in the "Artist Website" box?  Is there a way we should be formatting all web links in Wordpress so that they successfully open?  I'm noticing that there are some very subtle differences in how we enter information for the new website than what we had done before so it's possible we're doing something wrong on our end here."

**Comment by dstrogiy** [comment]
![aiflehj](https://cloud.githubusercontent.com/assets/6132788/10368536/b447c9b0-6da3-11e5-9972-fd841dbf3a9f.gif)
