### ISSUE TITLE
Faculty Email Links

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/Sculpture-2015#64]
http://arts.vcu.edu/sculpture/faculty/

"We're realizing we should have built in a link to each faculty member's email address.  It seems that all that information is still in Wordpress.  Can we make it so that these emails appear under the "VISIT WEBSITE" link for each faculty member?  Right now there is nowhere on our site that has this information.  This was our oversight in the initial design. (So sorry!!)"

**Comment by dstrogiy** [comment]
![robford10](https://cloud.githubusercontent.com/assets/6132788/10368692/8d62cec0-6da4-11e5-84eb-219e2d0f4a5a.gif)
