### ISSUE TITLE
Keep Faculty, Alumni, etc templates DRY 

### ISSUE THREAD

**Issue by streeetlamp** [VCUarts/Sculpture-2015#9]
Note to selves 

The faculty, alumni and possibly other pages will share a very similar layout structure. Currently archive-faculty.php exists but if this also mostly applies to alumni we should share same template or at least most of it. Gotta keep it DRY

**Comment by dstrogiy** [comment]
The single.php will be pretty much same for faculty & alumni. Not sure what visiting artists will look like, but will probably be v similar
